# This is a basic workflow that is manually triggered

name: Create Executables

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-linux-image:
    name: 'Build Linux Image'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Java 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: 'Setup GraalVM Environment'
        uses: DeLaGuardo/setup-graalvm@3.0
        with:
          graalvm-version: '20.3.0.java11'

      - name: 'Install Native Image Plugin'
        run: |
          gu install native-image    

      - name: 'Build Native Image'
        run: ./mvnw package -P native-image
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Upload'
        uses: actions/upload-artifact@v2
        with:
          name: alps
          path: ./alps-cli/target/alps
